### ISSUE TITLE
和webview冲突，出现运行时异常

### ISSUE THREAD

**Issue by yxnxiao** [SherlockGougou/BigImageViewPager#101]
android.view.InflateException: Binary XML file line #23: Error inflating class wendu.dsbridge.DWebView

     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
        at com.example.lhp.base.BaseBridgeWebViewFragment.onCreate(BaseBridgeWebViewFragment.java:70) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838) 
        at androidx.fragment.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1197) 
        at androidx.fragment.app.FragmentTransition.calculateFragments(FragmentTransition.java:1080) 
        at androidx.fragment.app.FragmentTransition.startTransitions(FragmentTransition.java:119) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824) 
        at androidx.fragment.app.FragmentManagerImpl.execSingleAction(FragmentManagerImpl.java:1696) 
        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:299) 
        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:259) 
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1244) 
        at androidx.viewpager.widget.ViewPager.populate(ViewPager.java:1092) 
        at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:540) 
        at com.example.lhp.fragment.FragmentBeautyLeadNews.initViewPager(FragmentBeautyLeadNews.java:250) 
        at com.example.lhp.fragment.FragmentBeautyLeadNews.access$300(FragmentBeautyLeadNews.java:45) 
        at com.example.lhp.fragment.FragmentBeautyLeadNews$3.onRequestSuccess(FragmentBeautyLeadNews.java:167) 
        at com.example.lhp.base.HttpActivity$3.onSuccess(HttpActivity.java:417) 
        at com.lzy.okgo.cache.policy.NoCachePolicy$1.run(NoCachePolicy.java:43) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:155) 
        at android.app.ActivityThread.main(ActivityThread.java:5696) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824) 
     Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x4040002
        at android.content.res.Resources.getText(Resources.java:300)
        at android.content.res.Resources.getString(Resources.java:386)
        at com.android.org.chromium.content.browser.ContentViewCore.setContainerView(ContentViewCore.java:702)
        at com.android.org.chromium.content.browser.ContentViewCore.initialize(ContentViewCore.java:608)
        at com.android.org.chromium.android_webview.AwContents.createAndInitializeContentViewCore(AwContents.java:619)

**Comment by SherlockGougou** [comment]
#0x4040002

你找一下编译生成的这个id对应的string是什么呢。

**Comment by SherlockGougou** [comment]
我这边看您没回复，先关闭了。如果有问题可以再打开。
