### ISSUE TITLE
点击相册选图，崩溃

### ISSUE THREAD

**Issue by keybalabala** [SherlockGougou/BigImageViewPager#117]
![微信截图_20201030165656](https://user-images.githubusercontent.com/22448830/97680104-1fdd0e80-1ad1-11eb-8620-414e6b905225.png)

**Comment by keybalabala** [comment]
W/ExifInterface: Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
    java.io.IOException: Invalid byte order: 424d
        at android.media.ExifInterface.readByteOrder(ExifInterface.java:3128)
        at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2443)
        at android.media.ExifInterface.getMimeType(ExifInterface.java:2321)
        at android.media.ExifInterface.loadAttributes(ExifInterface.java:1755)
        at android.media.ExifInterface.initForFilename(ExifInterface.java:2303)
        at android.media.ExifInterface.<init>(ExifInterface.java:1386)
        **at cc.shinichi.library.tool.image.ImageUtil.getOrientation(ImageUtil.java:74)**
        at cc.shinichi.library.tool.image.ImageUtil.getWidthHeight(ImageUtil.java:137)
        at cc.shinichi.library.tool.image.ImageUtil.isLongImage(ImageUtil.java:145)
        at cc.shinichi.library.view.ImagePreviewAdapter.setImageSpec(ImagePreviewAdapter.java:403)
        at cc.shinichi.library.view.ImagePreviewAdapter.loadImageStandard(ImagePreviewAdapter.java:437)
        at cc.shinichi.library.view.ImagePreviewAdapter.loadSuccess(ImagePreviewAdapter.java:396)
        at cc.shinichi.library.view.ImagePreviewAdapter.access$100(ImagePreviewAdapter.java:52)
        at cc.shinichi.library.view.ImagePreviewAdapter$7.onResourceReady(ImagePreviewAdapter.java:341)
        at cc.shinichi.library.view.ImagePreviewAdapter$7.onResourceReady(ImagePreviewAdapter.java:312)
