### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by SkyFlyTang** [SherlockGougou/BigImageViewPager#13]
11-23 12:54:11.025 27152-27152/com.yf.yftrace.app.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yf.yftrace.app.dev, PID: 27152
    java.lang.NoSuchFieldError: No static field rootView of type I in class Lcc/shinichi/library/R$id; or its superclasses (declaration of 'cc.shinichi.library.R$id' appears in /data/app/com.yf.yftrace.app.dev-1/split_lib_slice_8_apk.apk)
        at cc.shinichi.library.view.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:126)
        at android.app.Activity.performCreate(Activity.java:6355)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2438)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2545)
        at android.app.ActivityThread.access$1100(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1396)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5597)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:771)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:649)
11-23 12:54:11.108 1468-1618/? E/InputDispatcher: channel '827302d com.yf.yftrace.app.dev/com.yf.yftrace.arms.mvp.ui.activity.PestAddActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-23 12:54:11.200 393-393/? E/HAL: Dawei load: module=/system/lib64/hw/gralloc.msm8937.so

**Comment by SherlockGougou** [comment]
你好，请问是在什么情况下出现的？可以贴一下调用的代码嘛？

**Comment by SkyFlyTang** [comment]
是这样的  这种情况的发生比较极端，如果用的第三方库和你的这个库的xml有一样名次的layout

**Comment by SkyFlyTang** [comment]
activity_preview 这个layout文件和其他第三方的名次一样就出现这个问题

**Comment by SkyFlyTang** [comment]
我自己clone下来，把activity_preview 这个改个名称就没有问题了
