### ISSUE TITLE
大神，我之前用这个框架一直没问题，最近莫名其妙报错，错误信息如下

### ISSUE THREAD

**Issue by dary123** [SherlockGougou/BigImageViewPager#14]
java.lang.NoSuchMethodError: No virtual method addListener(Lcom/bumptech/glide/request/RequestListener;)Lcom/bumptech/glide/RequestBuilder; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.vc.app-2/base.apk:classes9.dex)
        at cc.shinichi.library.view.ImagePreviewAdapter.instantiateItem(ImagePreviewAdapter.java:201)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1158)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:19886)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:19886)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:19886)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19886)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19886)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19886)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6085)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:693)
        at android.view.View.measure(View.java:19886)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2316)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1407)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1660)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1295)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6400)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:876)
        at android.view.Choreographer.doCallbacks(Choreographer.java:688)
        at android.view.Choreographer.doFrame(Choreographer.java:623)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:862)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:163)
        at android.app.ActivityThread.main(ActivityThread.java:6239)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

定位到的代码   Glide.with(activity).downloadOnly().load(url).addListener(new RequestListener<File>() {
        @Override public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<File> target,
            boolean isFirstResource) {

**Comment by dary123** [comment]
已解决，glide版本改为4.8.0就没问题了

**Comment by dary123** [comment]
但是还是有问题，引入新版本v2.2.0新增：支持gif，报错AGPBI: {"kind":"error","text":"error:，好像是因为框架引用的jar包与我自己项目中的冲突，新版本是增加了什么库吗，之前老版本导入没有问题，我换回老版本就正常了
