### ISSUE TITLE
GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.

### ISSUE THREAD

**Issue by haoguibao** [SherlockGougou/BigImageViewPager#143]
glide版本 4.11.0
引用implementation 'com.github.SherlockGougou:BigImageViewPager:androidx-6.1.5'
MyAppGlideModule已添加
求教，当加载图片时，报错如下：

java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:344)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:336)
        at com.bumptech.glide.Glide.get(Glide.java:179)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:749)
        at com.bumptech.glide.Glide.with(Glide.java:776)
        at com.jess.arms.http.imageloader.glide.GlideArms.with(GlideArms.java:88)
        at com.jess.arms.http.imageloader.glide.GlideImageLoaderStrategy.loadImage(GlideImageLoaderStrategy.java:61)
        at com.jess.arms.http.imageloader.glide.GlideImageLoaderStrategy.loadImage(GlideImageLoaderStrategy.java:51)
        at com.jess.arms.http.imageloader.ImageLoader.loadImage(ImageLoader.java:57)

**Comment by haoguibao** [comment]
解决了，之前引的其它包里也有Glide的相关引用，造成GeneratedAppGlideModuleImpl异常。
解决方案：把有重复引用的Glide的依赖包里剔除对Glide的引用。
