### ISSUE TITLE
这个 NPE 可否遇到，"java.lang.NullPointerException: charset == null"

### ISSUE THREAD

**Issue by imtianx** [SherlockGougou/BigImageViewPager#168]
完整日志：

```
Back traces starts.
java.lang.NullPointerException: charset == null
	at java.lang.String.getBytes(String.java:940)
	at okio.-Platform.asUtf8ToByteArray(-Platform.kt:22)
	at okio.ByteString$Companion.encodeUtf8(ByteString.kt:342)
	at okhttp3.internal.http2.Header.<init>(Header.kt:33)
	at okhttp3.internal.http2.Http2ExchangeCodec$Companion.http2HeadersList(Http2ExchangeCodec.kt:162)
	at okhttp3.internal.http2.Http2ExchangeCodec.writeRequestHeaders(Http2ExchangeCodec.kt:75)
	at okhttp3.internal.connection.Exchange.writeRequestHeaders(Exchange.kt:59)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:36)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at cc.shinichi.library.glide.progress.ProgressManager$2.intercept(ProgressManager.java:51)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Back traces ends.
``

**Comment by SherlockGougou** [comment]
这边先关了，有问题再开。
