### ISSUE TITLE
这个 OOM 是否有解决的办法?

### ISSUE THREAD

**Issue by BruceWu16** [SherlockGougou/BigImageViewPager#169]
Caused by java.lang.OutOfMemoryError
Failed to allocate a 1073745680 byte allocation with 10731678 free bytes and 501MB until OOM, target footprint 21463358, growth limit 536870912

cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.getExifOrientation (SubsamplingScaleImageViewDragClose.java:1792)

**Comment by BruceWu16** [comment]
完整日志
Caused by java.lang.OutOfMemoryError: Failed to allocate a 1073745680 byte allocation with 8026584 free bytes and 376MB until OOM, max allowed footprint 16053168, growth limit 402653184
       at androidx.exifinterface.media.ExifInterface.readImageFileDirectory(ExifInterface.java:6956)
       at androidx.exifinterface.media.ExifInterface.readImageFileDirectory(ExifInterface.java:6997)
       at androidx.exifinterface.media.ExifInterface.readImageFileDirectory(ExifInterface.java:6938)
       at androidx.exifinterface.media.ExifInterface.readExifSegment(ExifInterface.java:6721)
       at androidx.exifinterface.media.ExifInterface.getJpegAttributes(ExifInterface.java:5640)
       at androidx.exifinterface.media.ExifInterface.loadAttributes(ExifInterface.java:4607)
       at androidx.exifinterface.media.ExifInterface.initForFilename(ExifInterface.java:5295)
       at androidx.exifinterface.media.ExifInterface.<init>(ExifInterface.java:3952)
       at cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.getExifOrientation(SubsamplingScaleImageViewDragClose.java:1792)
       at cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.access$5300(SubsamplingScaleImageViewDragClose.java:79)
       at cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose$TilesInitTask.doInBackground(SubsamplingScaleImageViewDragClose.java:3075)
       at cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose$TilesInitTask.doInBackground(SubsamplingScaleImageViewDragClose.java:3046)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**Comment by SherlockGougou** [comment]
您好，请问这个图片的尺寸有多大呢？可以提供一下url吗？

**Comment by BruceWu16** [comment]
> 你好，请问这张图片的尺寸有多大呢？

这个在后台收集的 , 只知道有内存泄露 , 但是应该不是大图

**Comment by SherlockGougou** [comment]
再遇到问题再开，这边先关闭了。
