### ISSUE TITLE
和另外一个九宫格库冲突..

### ISSUE THREAD

**Issue by sinkkin** [SherlockGougou/BigImageViewPager#19]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xunqi.mm/cc.shinichi.library.view.ImagePreviewActivity}: java.lang.ClassCastException: com.lzy.ninegrid.preview.HackyViewPager cannot be cast to cc.shinichi.library.view.HackyViewPager
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2593)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2653)
        at android.app.ActivityThread.access$900(ActivityThread.java:173)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:5726)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: java.lang.ClassCastException: com.lzy.ninegrid.preview.HackyViewPager cannot be cast to cc.shinichi.library.view.HackyViewPager
        at cc.shinichi.library.view.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:123)
        at android.app.Activity.performCreate(Activity.java:6350)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1121)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2546)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2653) 
        at android.app.ActivityThread.access$900(ActivityThread.java:173) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1431) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:5726) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622) 
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by sinkkin** [comment]
冲突的库 地址是https://github.com/jeasonlzy/NineGridView

**Comment by sinkkin** [comment]
最新版已经解决 感谢作者
