### ISSUE TITLE
友盟报了一个错，如下，imagepreview里有空指针异常

### ISSUE THREAD

**Issue by dary123** [SherlockGougou/BigImageViewPager#24]
1
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xindonshisan.ThireteenFriend/cc.shinichi.library.view.ImagePreviewActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
2
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3303)
3
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
4
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5477)
5
    at android.app.ActivityThread.-wrap19(Unknown Source:0)
6
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2000)
7
    at android.os.Handler.dispatchMessage(Handler.java:108)
8
    at android.os.Looper.loop(Looper.java:166)
9
    at android.app.ActivityThread.main(ActivityThread.java:7529)
10
    at java.lang.reflect.Method.invoke(Native Method)
11
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
12
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
13
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
14
    at cc.shinichi.library.view.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:118)
15
    at android.app.Activity.performCreate(Activity.java:7383)
16
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
17
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
18
    ... 10 more
19
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
20
    at cc.shinichi.library.view.ImagePreviewActivity.onCreate(ImagePreviewActivity.java:118)
21
    at android.app.Activity.performCreate(Activity.java:7383)
22
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
23
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
24
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3411)
25
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5477)
26
    at android.app.ActivityThread.-wrap19(Unknown Source:0)
27
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2000)
28
    at android.os.Handler.dispatchMessage(Handler.java:108)
29
    at android.os.Looper.loop(Looper.java:166)
30
    at android.app.ActivityThread.main(ActivityThread.java:7529)
31
    at java.lang.reflect.Method.invoke(Native Method)
32
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
33
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by SherlockGougou** [comment]
请问友盟统计到的这个频率高吗？

**Comment by jemon9** [comment]
很高，这个问题占我们app的top1

**Comment by SherlockGougou** [comment]
最新的3.2.2 对这个问题进行优化了，你可以升级后再观察观察。有问题及时反馈，感谢！
