### ISSUE TITLE
java.lang.NoSuchMethodError: com.bumptech.glide.util.LruCache.<init>

### ISSUE THREAD

**Issue by manburenshenglu** [SherlockGougou/BigImageViewPager#43]
Process: com.jaagro.driver, PID: 12805
    java.lang.NoSuchMethodError: com.bumptech.glide.util.LruCache.<init>
        at cc.shinichi.library.glide.cache.SafeKeyGenerator.<init>(SafeKeyGenerator.java:17)
        at cc.shinichi.library.glide.ImageLoader.getGlideCacheFile(ImageLoader.java:30)
        at cc.shinichi.library.view.ImagePreviewAdapter.instantiateItem(ImagePreviewAdapter.java:276)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1004)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1152)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
        at android.view.View.measure(View.java:16513)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
        at android.view.View.measure(View.java:16513)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:141)
        at android.view.View.measure(View.java:16513)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
        at android.view.View.measure(View.java:16513)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at android.view.View.measure(View.java:16513)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
        at android.view.View.measure(View.java:16513)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2367)
        at android.view.View.measure(View.java:16513)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1962)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1159)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1341)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1046)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5665)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
        at android.view.Choreographer.doFrame(Choreographer.java:544)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5135)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by SherlockGougou** [comment]
使用glide 4.8.0再试试

**Comment by manburenshenglu** [comment]
楼主，我把你的源码拉到本地了
![image](https://user-images.githubusercontent.com/13146756/55465732-54a48d80-5630-11e9-9873-49dd893d111d.png)

**Comment by manburenshenglu** [comment]
已经4.8.0了，还是不行

**Comment by SherlockGougou** [comment]
拉下来直接运行 就报错吗？

**Comment by manburenshenglu** [comment]
拉下来你的包直接运行没报错，我把你源码里面的library引入到我的项目中，查看大图就报错了

**Comment by SherlockGougou** [comment]
按照README里的说明，对你的app进行配置了吗？

**Comment by manburenshenglu** [comment]
我没有直接添加你框架的依赖，而是把你的源码创建一个module，然后我的项目依赖这个module。也需要配置吗？

**Comment by SherlockGougou** [comment]
library中的依赖都是compileOnly，仅仅参与编译；你还是需要配置那些依赖。

**Comment by manburenshenglu** [comment]
![image](https://user-images.githubusercontent.com/13146756/55467105-296f6d80-5633-11e9-872f-b0902e3118ac.png)
这样依赖直接报错了

**Comment by SherlockGougou** [comment]
请问这个问题 你解决了吗？

**Comment by HopeZZZ** [comment]
我遇到了这个问题，并且解决了它：
1.升级到glide4.8.
2.加入glide compiler.
