### ISSUE TITLE
重复的图片链接，加载图片失败

### ISSUE THREAD

**Issue by linzhixin93** [SherlockGougou/BigImageViewPager#72]
ImagePreview.getInstance().setContext(MainActivity.this).setImageList(imageList).start();
imageList里面是多个重复的图片链接,
第一次显示正常，第二次滑动回来的时候一直显示loading，日志打印图片加载失败
日志 : 
E/SubsamplingScaleImageViewDragClose: Failed to load bitmap
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
        at cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose$BitmapLoadTask.doInBackground(SubsamplingScaleImageViewDragClose.java:3126)
        at cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose$BitmapLoadTask.doInBackground(SubsamplingScaleImageViewDragClose.java:3106)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by SherlockGougou** [comment]
正常来说，不会有多张重复的图片吧，内存的缓存的key使用的是url，如果重复的话，是会造成这种情况的。

**Comment by Mr-PolarBear** [comment]
大哥  我也碰到了    这个情况要考虑下   划几下就炸了- -

**Comment by SherlockGougou** [comment]
设计如此，实际使用中不会出现多个重复的图片链接。
