### ISSUE TITLE
加载网络长图时，等图片完成时，下拉准备退出还会显示那张长图，而不是上个界面。

### ISSUE THREAD

**Issue by CaiJinFu** [SherlockGougou/BigImageViewPager#76]
加载网络长图时，显示转圈圈，等图片完成时，显示图片，下拉准备退出时，不是显示的上个界面，而是那张长图，跟普通图片下载完成时下拉的效果不一致。松手退出可以正常的退出。

**Comment by SherlockGougou** [comment]
你好，请问运行Demo有问题吗？Demo中也有一张长图。如果也有问题，麻烦提供一下机型和系统Android版本。

**Comment by CaiJingFu** [comment]
> 你好，请问运行Demo有问题吗？Demo中也有一张长图。如果也有问题，麻烦提供一下机型和系统Android版本。

demo中的加载很快，我一进去就好了，所以跟我的有点不太一样。demo中没有问题。我的图需要下载挺久的，下载完成后就出现了那个问题

**Comment by SherlockGougou** [comment]
麻烦提供一下长图的地址：缩略图和原图地址；

**Comment by CaiJingFu** [comment]
> 麻烦提供一下长图的地址：缩略图和原图地址；

我发现问题所在了，是这样的，我传入了一个地址的集合，然后我点击进去的position不是这个，之后我切换到这张长图所在的position，他在加载，我又切换到别页，再切换回来，就出现这个问题了。是不是跟viewpager的加载有关？
长图地址：http://112.74.210.163:16820/message/3f171a97de2873ecfdea2d2fd13601c2gk9h/efzub55fe7eb4e7bd6e853062283a34a1b297iyr/6355504746144ca968f74853f977b230l2cgkyb0/677520191113171652460465985321

**Comment by SherlockGougou** [comment]
好的，大概知道原因了，我这边先看看。

**Comment by CaiJingFu** [comment]
> 好的，大概知道原因了，我这边先看看。

好的

**Comment by SherlockGougou** [comment]
再试一下最新版本看看呢。

**Comment by CaiJinFu** [comment]
> 再试一下最新版本看看呢。

刚试了最新版本 发生了奔溃
崩溃信息:
Can't create handler inside thread Thread[Thread-29,5,main] that has not called Looper.prepare()

类名:Handler.java

方法:<init>

行数:207

类型:java.lang.RuntimeException

时间:2020-10-16 16:57

设备名称:MI 8 SE

设备厂商:Xiaomi

系统版本:29

全部信息:
java.lang.RuntimeException: Can't create handler inside thread Thread[Thread-29,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:207)
	at android.os.Handler.<init>(Handler.java:119)
	at android.view.GestureDetector$GestureHandler.<init>(GestureDetector.java:298)
	at android.view.GestureDetector.<init>(GestureDetector.java:405)
	at android.view.GestureDetector.<init>(GestureDetector.java:386)
	at cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.setGestureDetector(SubsamplingScaleImageViewDragClose.java:585)
	at cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.reset(SubsamplingScaleImageViewDragClose.java:581)
	at cc.shinichi.library.view.helper.SubsamplingScaleImageViewDragClose.setOrientation(SubsamplingScaleImageViewDragClose.java:2618)
	at cc.shinichi.library.view.ImagePreviewAdapter.loadImageSpec(ImagePreviewAdapter.java:435)
	at cc.shinichi.library.view.ImagePreviewAdapter.loadSuccess(ImagePreviewAdapter.java:394)
	at cc.shinichi.library.view.ImagePreviewAdapter.access$100(ImagePreviewAdapter.java:52)
	at cc.shinichi.library.view.ImagePreviewAdapter$7$1.run(ImagePreviewAdapter.java:325)
	at java.lang.Thread.run(Thread.java:919)

使用场景是这样的，传进去查看的position是一张不大的图，然后我又滑到那张长图，他在转圈加载，我又滑到别的地方，再滑回来，如此反复。就奔溃了。
