### ISSUE TITLE
glide 报错了。

### ISSUE THREAD

**Issue by lbx2015** [SherlockGougou/BigImageViewPager#80]
java.lang.IllegalStateException: Unable to extract the trust manager on AndroidPlatform, sslSocketFactory is class com.networkbench.agent.impl.socket.CustomSSLSocketFactory
        at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:162)
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:691)
        at cc.shinichi.library.glide.sunfusheng.progress.ProgressManager.getOkHttpClient(ProgressManager.java:53)
        at cc.shinichi.library.glide.sunfusheng.progress.ProgressLibraryGlideModule.registerComponents(ProgressLibraryGlideModule.java:21)
        at com.bumptech.glide.GeneratedAppGlideModuleImpl.registerComponents(GeneratedAppGlideModuleImpl.java:33)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:302)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:239)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:198)
        at com.bumptech.glide.Glide.get(Glide.java:179)
        at com.bumptech.glide.Glide.getRetriever(Glide.java:714)
        at com.bumptech.glide.Glide.with(Glide.java:741)

**Comment by SherlockGougou** [comment]
请提供一下具体的机型、Android版本、依赖的配置
