### ISSUE TITLE
Gif问题

### ISSUE THREAD

**Issue by ArcGhh** [SherlockGougou/BigImageViewPager#82]
加载gif图时，glide加载崩溃。可能是glide版本不一样，diskCacheStrategy报异常。
我这边这样写可以：
Glide.with(activity).asGif().diskCacheStrategy(DiskCacheStrategy.AUTOMATIC)
                .load(imagePath).apply(new RequestOptions()
                .error(ImagePreview.getInstance().getErrorPlaceHolder()))
               .into(iv);

**Comment by rosuH** [comment]
加载 Gif 有同样的问题。
- Glide 版本 4.9.0
- BigImageViewPager 版本：v4_6.0.0

```
java.lang.NoSuchMethodError: No virtual method diskCacheStrategy(Lcom/bumptech/glide/load/engine/DiskCacheStrategy;)Lcom/bumptech/glide/request/RequestOptions; in class Lcom/bumptech/glide/request/RequestOptions; or its super classes (declaration of 'com.bumptech.glide.request.RequestOptions' appears in /data/app/com.lizhiweike-2/base.apk:classes23.dex)
        at cc.shinichi.library.view.ImagePreviewAdapter.loadGifImageSpec(ImagePreviewAdapter.java:535)
        at cc.shinichi.library.view.ImagePreviewAdapter.instantiateItem(ImagePreviewAdapter.java:298)
        at android.support.v4.view.ViewPager.addNewItem(ViewPager.java:1010)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1158)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1092)
        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1622)
        at android.view.View.measure(View.java:19931)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:19931)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
        at android.view.View.measure(View.java:19931)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1485)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
        at android.view.View.measure(View.java:19931)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19931)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1485)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:775)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:657)
        at android.view.View.measure(View.java:19931)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6139)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:729)
        at android.view.View.measure(View.java:19931)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2442)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1488)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1747)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1372)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6774)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:926)
        at android.view.Choreographer.doCallbacks(Choreographer.java:735)
        at android.view.Choreographer.doFrame(Choreographer.java:667)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:912)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

**Comment by rosuH** [comment]
项目降级 Glide 到 4.9 就解决了，原因应该是 `RequestOptions` 这个类在两个版本间有了较大的变更。
1. 4.8 中 `RequestOptions` 直接继承了`Cloneable`

```
// RequestOptions.java#137
@NonNull
@CheckResult
public static RequestOptions diskCacheStrategyOf(@NonNull DiskCacheStrategy diskCacheStrategy) {
    return new RequestOptions().diskCacheStrategy(diskCacheStrategy);
}

// 调用同类 RequestOptions.java#532
@NonNull
@CheckResult
  public RequestOptions diskCacheStrategy(@NonNull DiskCacheStrategy strategy) {
    if (isAutoCloneEnabled) {
      return clone().diskCacheStrategy(strategy);
    }
    this.diskCacheStrategy = Preconditions.checkNotNull(strategy);
    fields |= DISK_CACHE_STRATEGY;

    return selfOrThrowIfLocked();
}
```

2. 4.9.0 中已经抽离了出`BaseRequestOptions`，所以`diskCacheStrategy(@NonNull DiskCacheStrategy strategy) ` 方法也在`BaseRequestOptions`中。
导致了 `java.lang.NoSuchMethodError: No virtual method diskCacheStrategy` 的错误。

4.9.0 的更新允许调用者直接使用流式 API 来应用旧版本的 `RequestOptions` 而不需要使用 `apply`，所以建议作者升级到 4.9.0。（https://github.com/bumptech/glide/releases/tag/v4.9.0）

我看了知乎的 [Matisse](https://github.com/zhihu/Matisse/blob/master/matisse/build.gradle) 也是升级到 4.9.0 了的。
